<?php 
$title = "home";
include('includes/header.php');
?>



<nav class="navbar navbar-expand-lg bg-white">
	<div class="container-fluid px-4">
		<!-- Brand -->
		<a class="navbar-brand ml-3" href="#">
			<img src="imgs/A_1024x1024.png" style="max-height: 80px">
		</a>

		<!-- Links -->
		<ul class="navbar-nav ml-auto">
			<li class="nav-item">
				<a class="btn bgn-lg my-btn m-3 px-5" href="#">Contact</a>
			</li>
			<li class="nav-item">
				<a class="btn bgn-lg my-btn-outline fw-bold m-3 px-5" href="login.php">Login</a>
			</li>
		</ul>
	</div>
</nav>
<div class="hero_rapper">
	<div class="container py-5">
		<div class="row align-items-center">
			<div class="col-md-8  text-white" style="text-shadow: 2px 2px 4px #000000;">
				<div style="">
					<h2 class="">Welcome to</h2>
					<h1 class="display-3 ">E-Church Management System</h1>
					<i><h3>Use technology to effectively manage and grow your iminstry.</h3></i>
				</div>
			</div>
			<div class="col-md-4">
				<div class="row">
					<div class="col-md-12 px-2" >
						<div class="card round-card" >
							<div class="card-body">
								<h2 class="bolder">Why this ECMS?</h2>
								<br>
								<ul class="mb-3  text-secondary mylist1" >
									<li>Scalable</li>
									<li>Fast</li>
									<li>Accurate</li>
									<li>Widely used</li>
									<li>Stable</li>
								</ul>

								<a class="btn bgn-lg my-btn btn-block fw-bold  px-5" href="login.php">Login</a>

								<div class="text-center p-2">
									<small class="mt-3">
										This application is made/develope and published by Tarnue Pythagoras borbor.
									</small>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div style="background: rgba(217,238,225,.3)">
	<div class="container py-3">
		<div class="row py-5">
			<div class="col-sm-6 col-md-4 text-center">
				<i class="fa fa-users fa-3x text-secondary" aria-hidden="true"></i>
				<h3 class=" my-color mb-0">Manage Members</h3>
				<p>including members, and all orders department</p>
			</div>
			<div class="col-sm-6 col-md-4 text-center">
			<i class="fa fa-calendar fa-3x text-secondary" aria-hidden="true"></i>
				<h3 class=" my-color mb-0 ">Financial Tracking</h3>
				<p>Record and keep track of all monetary tranaction</p>
			</div>
			<div class="col-sm-6 col-md-4 text-center">
				<i class="fa fa-line-chart fa-3x text-secondary" aria-hidden="true"></i>
				<h3 class=" my-color mb-0">Easy Report</h3>
				<p>Generate Financial reports quickly and accurately</p>
			</div>
		</div>
	</div>
</div>

<div class="container-fluid bg-white py-5">
	<div class="row py-5">
		<div class="col-12 text-center mb-4">
			<h3 class="display-4 my-color">Breaf Summary E-Church Manager</h3>
			<p class="lead">E-Church manager is a software designed to manage your church members, financial record and generate instant report.</p>
		</div>
		<div class="col-md-8 offset-md-2">
			<div class="container-fluid">
			<video width="100%" height="100%" autoplay muted loop>
  <source src="imgs/bandicam 2021-09-07 02-14-09-735.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
Your browser does not support the video tag.
</video>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4 offset-md-4 text-center">
			<a href="github.com/tarnuepborbor" class="my-btn btn-block py-2 mb-4">Get More Appps </a>
			<small>
				Above is a screenshoot of sample but accurate fanancial report generated by E-Church Manager within just few clicks
			</small>
		</div>
	</div>
</div>










<?php 

include("includes/footer.php");